spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  profiles:
    include: aws, info, s3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
