spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kelog
    username: root
    password: 12345678
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
server:
  port: 4000